// Package detect is the router: it walks the repo and reports which ecosystems
// are present, so the runner only invokes the scanners that apply. Manifest /
// lockfile filenames are the precise trigger for tool selection; go-enry
// (GitHub Linguist's data) adds vendored/generated filtering and a language
// census so scans skip third-party + machine-generated files.
package detect

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	enry "github.com/go-enry/go-enry/v2"
)

// Ecosystem is a detected language/format family.
type Ecosystem string

const (
	Go        Ecosystem = "go"
	Node      Ecosystem = "node"
	Python    Ecosystem = "python"
	Terraform Ecosystem = "terraform"
	Docker    Ecosystem = "docker"
)

// Result is the set of detected ecosystems, whether any dependency
// lockfile/manifest exists (the trigger for SCA tools), whether the repo has
// GitHub Actions workflows (the trigger for zizmor), and a language census.
type Result struct {
	Ecosystems   map[Ecosystem]bool
	HasLockfile  bool
	HasWorkflows bool
	Languages    map[string]int // enry language name -> file count (non-vendored)
}

// Has reports whether ecosystem e was detected.
func (r Result) Has(e Ecosystem) bool { return r.Ecosystems[e] }

// manifestMarkers maps an exact filename to the ecosystem it implies.
var manifestMarkers = map[string]Ecosystem{
	"go.mod":           Go,
	"package.json":     Node,
	"requirements.txt": Python,
	"pyproject.toml":   Python,
	"setup.py":         Python,
	"Pipfile":          Python,
	"Dockerfile":       Docker,
}

// suffixMarkers maps a filename suffix to the ecosystem it implies.
var suffixMarkers = map[string]Ecosystem{
	".tf":         Terraform,
	".dockerfile": Docker,
}

// lockfiles indicate a resolved dependency tree worth SCA scanning.
var lockfiles = map[string]bool{
	"go.sum":            true,
	"package-lock.json": true,
	"yarn.lock":         true,
	"pnpm-lock.yaml":    true,
	"poetry.lock":       true,
	"uv.lock":           true,
	"Pipfile.lock":      true,
	"requirements.txt":  true,
	"Gemfile.lock":      true,
	"Cargo.lock":        true,
}

// Detect walks an on-disk root.
func Detect(root string, ignore []string) (Result, error) {
	return walk(os.DirFS(root), ignore)
}

// DetectFS walks an fs.FS (used by tests). Behaviour matches Detect.
func DetectFS(fsys fs.FS, ignore []string) (Result, error) {
	return walk(fsys, ignore)
}

// walk is the shared traversal: skip ignored dirs and enry-vendored files, then
// classify each remaining file.
func walk(fsys fs.FS, ignore []string) (Result, error) {
	res := Result{Ecosystems: map[Ecosystem]bool{}, Languages: map[string]int{}}
	ignoreSet := make(map[string]bool, len(ignore))
	for _, ig := range ignore {
		ignoreSet[ig] = true
	}
	err := fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != "." && ignoreSet[d.Name()] {
				return fs.SkipDir
			}
			return nil
		}
		// Workflow detection runs before the vendor filter: enry classifies
		// .github/ as vendored, which would otherwise suppress it. fs.FS paths
		// are always slash-separated, so a prefix check is exact.
		if strings.HasPrefix(path, ".github/workflows/") {
			lower := strings.ToLower(d.Name())
			if strings.HasSuffix(lower, ".yml") || strings.HasSuffix(lower, ".yaml") {
				res.HasWorkflows = true
			}
		}
		// Vendored files are skipped entirely: a vendored go.mod must not
		// trigger Go, etc.
		if enry.IsVendor(path) {
			return nil
		}
		// Ecosystem + lockfile signals are recorded even for enry-"generated"
		// files: lockfiles (package-lock.json, pnpm-lock.yaml, Pipfile.lock) are
		// generated by definition yet are exactly the SCA trigger, so gating them
		// behind IsGenerated would silently disable osv-scanner for npm/pnpm/pipenv.
		classifyManifest(d.Name(), &res)
		// The language census excludes generated (machine-emitted) files.
		if !enry.IsGenerated(path, nil) {
			if lang := enry.GetLanguage(filepath.Base(path), nil); lang != "" {
				res.Languages[lang]++
			}
		}
		return nil
	})
	return res, err
}

// classifyManifest records ecosystem + lockfile signals for one file by name.
// The language census lives in walk (it is gated on IsGenerated, these signals
// are not).
func classifyManifest(name string, res *Result) {
	if e, ok := manifestMarkers[name]; ok {
		res.Ecosystems[e] = true
	}
	lower := strings.ToLower(name)
	for suf, e := range suffixMarkers {
		if strings.HasSuffix(lower, suf) {
			res.Ecosystems[e] = true
		}
	}
	if lockfiles[name] {
		res.HasLockfile = true
	}
}
